better caches?

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -16,7 +16,8 @@ jobs:
       - checkout
       - restore_cache:
           keys:
-            - v1-gradle-cache-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
+            - gradle-cache-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
+            - gradle-cache-
       - run:
           name: Build APK
           command: ./gradlew assembleDebug
@@ -24,7 +25,7 @@ jobs:
           paths:
             - ~/.gradle/caches
             - ~/.gradle/wrapper
-          key: v1-gradle-cache-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
+          key: gradle-cache-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
       - store_artifacts:
           path: app/build/outputs/apk/debug/app-debug.apk
           destination: app-debug.apk
@@ -37,15 +38,26 @@ jobs:
       - checkout
       - restore_cache:
           keys:
-            - v1-gradle-cache-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
+            - gradle-cache-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
+            - gradle-cache-
+      - run:
+          name: Ensure gradlew is runnable
+          commad: |
+            if [ -f "./gradlew" ]; then
+              chmod +x ./gradlew
+              echo "gradlew is now executable."
+            else
+              echo "gradlew not found!"
+              exit 1
+            fi
       - run:
           name: Run Unit Tests
-          command: chmod +x ./gradlew testDebugUnitTest
+          command: ./gradlew testDebugUnitTest
       - save_cache:
           paths:
             - ~/.gradle/caches
             - ~/.gradle/wrapper
-          key: v1-gradle-cache-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
+          key: gradle-cache-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
       - store_test_results:
           path: app/build/test-results/testDebugUnitTest
       - store_artifacts:
